# This setup is tested with NIVIDIA Driver Version: 530.41.03
# (and CUDA Version: 12.1, but that should be overridden by jax install)
name: dreamer-object-permanence
channels:
  # Order is important <https://github.com/google/jax#conda-installation>
  - default # We add this ourselves, cause we don't want Python/pip from forge (it crashes dreamerv3 installation).
  - conda-forge
  - nvidia
dependencies:
  - python=3.10
  - pip

  # Note: The config errored (for some fucking reason) on another machine, even with identical pip and setuptools versions etc.
  # Pinning this fixes the build of gym=0.19.0 (required by dreamerv3)
  - setuptools=65.5.0
  - wheel=0.38.4

  # Install JAX with GPU support first
  # <https://github.com/google/jax#conda-installation>
  - jaxlib=*=*cuda*
  - jax
  - cuda-nvcc

  # ... and the rest
  - pip:
      - dreamerv3
      - animalai

  # For default (higher) version, we get an error coming from ml-agents
  # This is the recommended approach from protobuf
  # - protobuf=3.20
  # NOTE: Solved (or avoided) by setting PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python
