# This setup is tested with NIVIDIA Driver Version: 530.41.03
# (and CUDA Version: 12.1, but that should be overridden by jax install)
name: dreamer-object-permanence
channels:
  # Order is important <https://github.com/google/jax#conda-installation>
  - default # We add this ourselves, cause we don't want Python/pip from forge (it crashes dreamerv3 installation).
  - conda-forge
  - nvidia
dependencies:
  # - python=3.10.8
  - python=3.9
  - pip

  # Note: The config errored (for some fucking reason) on another machine, even with identical pip and setuptools versions etc.
  # Pinning this fixes the build of gym=0.19.0 (required by dreamerv3)
  - setuptools=65.5.0
  - wheel=0.38.4

  # Install JAX with GPU support first
  # <https://github.com/google/jax#conda-installation>
  - jaxlib=*=*cuda*
  - jax
  - cuda-nvcc

  # ... and the rest
  - pip:
      - gym==0.19.0 # Pin manually for certainty
      - dreamerv3
      - gym-unity

      # The PyPI animalai package (https://pypi.org/project/animalai/) is outdated
      # and not maintained by LCFI/KoI anymore. The updated version comes from the
      # <https://github.com/Kinds-of-Intelligence-CFI/animal-ai> repo.
      #
      # However, we need an older version anyway (animalai <= 3.0.1), and the latest commit
      # I could find that does not need mlagents==0.30.0 is <https://github.com/Kinds-of-Intelligence-CFI/animal-ai/commit/5386a625dcd160b017e1be48c88897aa9fb20b3b>
      # See bottom of the file to see why we can't use mlagents==0.30.0.
      # Below is the conda alternative for `pip install ...`
      # - "git+https://github.com/Kinds-of-Intelligence-CFI/animal-ai.git@5386a625dcd160b017e1be48c88897aa9fb20b3b#egg=animalai&subdirectory=animalai"
      # - mlagents==0.27.0 (implied by dependency above)

      # However, ... this commit has an issue with the build, where the folder
      # structure is missing an __init__, causing the eggs/wheels to be empty.
      # We fix it by just copying the source at that point, and modifying it ourselves.
      # That source is commmitted in the repo.
      - "aai/animal-ai-5386a625dcd160b017e1be48c88897aa9fb20b3b/animalai/"

      # Better don't do this (this is the outdated PyPI package)
      # - animalai

  # Dev
  - mypy
  - autopep8
#
#
# -----------------------------
# Important version constraints
# -----------------------------

# animalai v3.0.2 requires mlagents 0.30.0
#     <https://github.com/Kinds-of-Intelligence-CFI/animal-ai>
# animalai v3.0.1 requires mlagents 0.27.0
#     <https://github.com/Kinds-of-Intelligence-CFI/animal-ai>
#     (Release 18 <https://github.com/Unity-Technologies/ml-agents/releases/tag/release_18>)
# dreamerv3 1.1.0 requires gym==0.19.0
#     <https://github.com/danijar/dreamerv3/blob/main/requirements.txt>
# mlagents-envs 0.30.0 requires gym>=0.21.0
#     <https://github.com/Unity-Technologies/ml-agents/blob/3fd3fdf1570b58109f5ad883b364b3526bc68ad7/ml-agents-envs/setup.py#L57>
#     ==> thus also mlagents 0.30.0, thus also animalai (GH) v3.0.2
# mlagents 0.30.0 requires Python >=3.8.13,<=3.10.8
#    <https://github.com/Unity-Technologies/ml-agents/blob/89a6357016f4bd685bb0004f83a3a1c2b27a0e05/ml-agents/setup.py>
# mlagents 0.27.0 requires Python >=3.6.1, but smaller than?
#    <https://github.com/Unity-Technologies/ml-agents/blob/c1b26d49e4f4fc692c2688531f9e7c69dba12682/ml-agents/setup.py>
# jax 0.4.14 requires Python > 3.8
#    <https://github.com/google/jax/blob/main/CHANGELOG.md>
# jax 0.4.14 requires numpy > 1.22
#    <https://github.com/google/jax/blob/main/CHANGELOG.md>
# jax 0.4.x requires high enough proto > 3.20
# protobuf 4.23 (latest version) is not compatible with the proto files generated by mlagents <= 0.30.0
#    Two options (provided by proto package)
#    1. Downgrade the proto package to 3.20.x or lower. (not compatible with decent jax versions)
#    2. Set PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python (but this will use pure-Python parsing and will be much slower).
#    -> the option we choose
# mlagents-envs 0.27.0 requries numpy < 1.20
#    Uses numpy.bool, which was deprecated in https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
#    Latest jax that allows a numpy < 1.20 is XXX with numpy>=1.19
#
# Question, does ml-agents=0.27.0 work with python 3.10.8?
#     Initially there were issues with torch install
#     => We got with python=3.9 instead
