!ArenaConfig
arenas:
  # SanityGreen: Randomized green goal and randomized agent
  0: !Arena
    pass_mark: 1
    t: 500
    items:
      - !Item
        name: Agent
        positions:
          - !Vector3 { x: -1, y: -1, z: -1 }
        rotations: [-1]
      - !Item
        name: GoodGoal
        positions:
          - !Vector3 { x: -1, y: -1, z: -1 }
        sizes:
          - !Vector3 { x: 2, y: 2, z: 2 }
  # Fixed agent, fixed button, very close
  1: !Arena
    pass_mark: 0
    t: 500
    items:
      - !Item
        name: Agent
        positions:
          - !Vector3 { x: 2, y: 0, z: 2 }
        rotations: [90]
      - !Item
        name: Pillar-Button
        positions:
          - !Vector3 { x: 6, y: 0, z: 2 }
        moveDurations: [0.1]
        resetDurations: [1.0]
        rewardNames: ["GoodGoal", "BadGoal", "GoodGoalMulti"]
        rewardWeights: [1, 0, 0]
        spawnProbability: 1.0
        rewardSpawnPos: !Vector3 { x: 8, y: 0, z: 8 }
  #  Randomized agent (fixed z-pos), fixed button and goal, close by
  2: !Arena
    pass_mark: 0
    t: 500
    items:
      - !Item
        name: Agent
        positions:
          - !Vector3 { x: -1, y: 0, z: 2 }
        rotations: [90]
      - !Item
        name: Pillar-Button
        positions:
          - !Vector3 { x: 15, y: 0, z: 10 }
        moveDurations: [0.1]
        resetDurations: [1.0]
        rewardNames: ["GoodGoal", "BadGoal", "GoodGoalMulti"]
        rewardWeights: [1, 0, 0]
        spawnProbability: 1.0
        rewardSpawnPos: !Vector3 { x: 14, y: 0, z: 14 }
  #  Randomized agent, randomized button, fixed goal
  3: !Arena
    pass_mark: 0
    t: 700
    items:
      - !Item
        name: Agent
        positions:
          - !Vector3 { x: -1, y: 0, z: -1 }
        rotations: [90]
      - !Item
        name: Pillar-Button
        positions:
          - !Vector3 { x: -1, y: 0, z: -1 }
        moveDurations: [0.1]
        resetDurations: [1.0]
        rewardNames: ["GoodGoal", "BadGoal", "GoodGoalMulti"]
        rewardWeights: [1, 0, 0]
        spawnProbability: 1.0
        rewardSpawnPos: !Vector3 { x: 20, y: 0, z: 20 }
  #  Randomized agent, randomized button, randomized goal
  4: !Arena
    pass_mark: 0
    t: 700
    items:
      - !Item
        name: Agent
        positions:
          - !Vector3 { x: -1, y: 0, z: -1 }
        rotations: [90]
      - !Item
        name: Pillar-Button
        positions:
          - !Vector3 { x: -1, y: 0, z: -1 }
        moveDurations: [0.1]
        resetDurations: [1.0]
        rewardNames: ["GoodGoal", "BadGoal", "GoodGoalMulti"]
        rewardWeights: [1, 0, 0]
        spawnProbability: 1.0
        rewardSpawnPos: !Vector3 { x: -1, y: 0, z: -1 }
