!ArenaConfig
arenas:
  0: !Arena
    pass_mark: 0
    t: 500
    items:
      - !Item
        name: Agent
        positions:
          - !Vector3 { x: 2, y: 0, z: -1 }
        rotations: [90]
      - !Item
        name: Pillar-Button
        positions:
          - !Vector3 { x: 20, y: 0, z: 20 }
        moveDurations: [0.1]
        resetDurations: [1.0]
        rewardNames: ["GoodGoal", "BadGoal", "GoodGoalMulti"]
        rewardWeights: [1, 0, 0]
        spawnProbability: 1.0
        rewardSpawnPos: !Vector3 { x: 30, y: 0, z: 35 }
  1: !Arena
    pass_mark: 0
    t: 500
    items:
      - !Item
        name: Agent
        positions:
          - !Vector3 { x: 2, y: 0, z: 2 }
        rotations: [90]
      - !Item
        name: Pillar-Button
        positions:
          - !Vector3 { x: 10, y: 0, z: 10 }
        moveDurations: [0.1]
        resetDurations: [1.0]
        rewardNames: ["GoodGoal", "BadGoal", "GoodGoalMulti"]
        rewardWeights: [1, 0, 0]
        spawnProbability: 1.0
        rewardSpawnPos: !Vector3 { x: 10, y: 0, z: 7 }
  2: !Arena
    pass_mark: 1
    t: 500
    items:
      - !Item
        name: Agent
        positions:
          - !Vector3 { x: -1, y: -1, z: -1 }
        rotations: [-1]
      - !Item
        name: GoodGoal
        positions:
          - !Vector3 { x: -1, y: -1, z: -1 }
        sizes:
          - !Vector3 { x: 2, y: 2, z: 2 }
